import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { stat } from "node:fs/promises";
import { join } from "node:path";
import { test } from "node:test";
import { pathToFileURL } from "node:url";
import { DiagnosticSeverity } from "vscode-languageserver-types";
import { LspSupervisor } from "../src/lsp/lsp-supervisor.js";
test("handshake, unsaved diagnostics, update, replay, and shutdown", { timeout: 90_000 }, async t => {
  const path = join(process.cwd(), `__virtual_${randomUUID()}.ts`);
  const uri = pathToFileURL(path).href;
  const supervisor = new LspSupervisor({ workspaceRoot: process.cwd() });
  t.after(() => supervisor.shutdown());
  await assert.rejects(stat(path), { code: "ENOENT" });
  await supervisor.start();
  await supervisor.openVirtualDocument(uri, "typescript", 1, "// UTF-8: café 🚀\nexport const broken = ;\n");
  const diagnostics = await supervisor.waitForDiagnostics(uri, 1, 20_000);
  assert.ok(diagnostics.some(d => d.severity === DiagnosticSeverity.Error));
  diagnostics.length = 0;
  assert.ok(supervisor.getDiagnostics(uri).length > 0);
  await supervisor.updateVirtualDocument(uri, 2, "export function broken( {\n");
  assert.ok((await supervisor.waitForDiagnostics(uri, 2, 20_000)).some(d => d.severity === DiagnosticSeverity.Error));
  await assert.rejects(supervisor.updateVirtualDocument(uri, 2, ""), /must exceed/);
  await supervisor.restart();
  assert.ok((await supervisor.waitForDiagnostics(uri, 2, 20_000)).some(d => d.severity === DiagnosticSeverity.Error));
  await supervisor.closeVirtualDocument(uri);
  assert.deepEqual(supervisor.getDiagnostics(uri), []);
  await assert.rejects(supervisor.waitForDiagnostics(uri, 2), /not open/);
  await supervisor.shutdown();
  await supervisor.shutdown();
  await assert.rejects(stat(path), { code: "ENOENT" });
});
